baseURL = 'https://cryptocode.github.io/blog/'
languageCode = 'en-us'
title = 'cryptocode'
theme = 'PaperMod'
[themeParams]
defaultTheme = 'dark'
disableThemeToggle = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2