baseURL = 'https://cryptocode.github.io/blog/'
languageCode = 'en-us'
title = " Roger's Blog"
theme = 'PaperMod'

[Params]
defaultTheme = 'dark'
disableThemeToggle = true
images = ["images/mondrian.png"]

[Params.label]
  icon = "images/mondrian.png"
  iconHeight = 35

[Params.homeInfoParams]
  title="Welcome!"
  content="Feel free to reach out to me on Discord (@cryptocode), IRC on Libera Chat (@cryptocode) or email me at cryptocode@zolo.io."

[Params.socialIcons]

  [Params.socialIcons.github]
    name="github"
    url="https://github.com/cryptocode"

  [Params.socialIcons.x]
    name="x"
    url="https://x.com/0xcafec0der"

  [Params.socialIcons.mastodon]
    name="mastodon"
    url="https://mastodon.social/@cryptocod3"

  [Params.socialIcons.rss]
    name="rss"
    url="https://cryptocode.github.io/blog/index.xml"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
