baseURL = 'https://cryptocode.github.io/blog/'
languageCode = 'en-us'
title = " Roger's Blog"
theme = 'PaperMod'

[Params]
defaultTheme = 'dark'
disableThemeToggle = true
images = ["images/mondrian.png"]

[Params.label]
  icon = "images/mondrian.png"
  iconHeight = 35

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
